FROM ghcr.io/mlflow/mlflow

WORKDIR /server

ARG USERNAME=admin
ARG USER_ID=1000
ARG GROUP_ID=1000

RUN addgroup --gid $GROUP_ID $USERNAME
RUN adduser --disabled-password --gecos '' --uid $USER_ID --gid $GROUP_ID $USERNAME
RUN chown $USER_ID:$GROUP_ID /server
USER $USERNAME

CMD mlflow server -h 0.0.0.0 -p 5000
